Add `embedded-hal-async` support
dbrgn/sgp30-rs pull request #19
Opened 2024-06-08 19:31 UTC by hawkw

This commit adds support for the `embedded-hal-async` crate in addition
to `embedded-hal`. I've done this by adding a separate `AsyncSgp30`
type, based on the assumption that most projects won't need to use both
the blocking `embedded-hal` traits and the `embedded-hal-async` traits
at the same time, and providing `async fn` methods on a separate type
with the same names as the blocking ones seemed a bit nicer than having
one type that has both `fn measure` and `async fn measure_async` and so
on. I've also factored out some of the no-IO code for packing and
unpacking Rust to/from bytes, so that it can be shared by both the async
and blocking driver types.

Support for `embedded-hal-async` is gated behind the
`embedded-hal-async` feature flag, so the dependency is not enabled by
default.

Note that this branch depends on my PR #18, which updates this crate to
use `embedded-hal` v1.0, and currently contains the commit from that 
change as well. Once #18 has merged, this branch will need to be rebased
onto the main branch.

It also depends on my upstream PR adding `embedded-hal-async` support to
`sensirion-i2c-rs`, sensirion/sensirion-i2c-rs#30, which has been
[merged], but hasn't been published to crates.io yet. Currently, this
branch adds a Cargo `[patch]` to use a Git dep on `sensirion-i2c-rs`.
So, this change cannot be released to crates.io until upstream publishes
a new release of `sensirion-i2c-rs`. Hopefully they do that soon! :)

[merged]: https://github.com/Sensirion/sensirion-i2c-rs/commit/f7b9f3a81b777bc6e6b2f0acb4c1ef9c57dfa06d

2024-06-30 21:46 UTC, dbrgn commented
Now that #18 is merged, I'll go ahead and will rebase this branch on top of the current `main` branch.

2024-06-30 22:27 UTC, dbrgn requested changes
Thanks for the PR, this looks nice!

I generally agree about the choices regarding a separate struct with methods of the same name. However, just to explore the available options: A third approach would be keeping the same shared `Sgp30` struct, but implementing both sync and async methods through two separate traits. One (and only one) of them would need to be imported to bring in the desired methods. The separate struct is probably better for ease-of use though. What are your thoughts on that?

Another thing I don't really like is how close-but-not-the-same the implementations are. I guess that's just how colored functions work in Rust. However, the commends are identical copies. Are you aware of a way to "inherit" docs of another method (maybe using a macro)?

2024-06-30 22:27 UTC, dbrgn commented on Cargo.toml
> +sensirion-i2c = { git = "https://github.com/sensirion/sensirion-i2c-rs", rev = "f7b9f3a81b777bc6e6b2f0acb4c1ef9c57dfa06d" }
Note to self: This should be removed before merging.

2024-06-30 22:27 UTC, dbrgn commented on src/lib.rs
> +const SELFTEST_SUCCESS: &[u8] = &[0xd4, 0x00];
Could you add a rustdoc comment explaining this magic number? (Previously it was obvious because it was part of the "selftest" command.) Maybe something like this?

```suggestion
/// The fixed data pattern returned when the on-chip self-test is successful.
const SELFTEST_SUCCESS: &[u8] = &[0xd4, 0x00];
```

2024-06-30 22:27 UTC, dbrgn commented on src/async_impl.rs
> +    // the ones in the `i2c` module.
embedded-hal-mock does have async support for the I2C mock since 0.11.0 if you enable the `embedded-hal-async` feature: https://github.com/dbrgn/embedded-hal-mock/blob/main/CHANGELOG.md (This is not obvious from the docs, those should probably be improved.)

Do you plan to add tests as part of this PR?

2024-07-19 21:30 UTC, dbrgn commented on Cargo.toml
> +sensirion-i2c = { git = "https://github.com/sensirion/sensirion-i2c-rs", rev = "f7b9f3a81b777bc6e6b2f0acb4c1ef9c57dfa06d" }
The sensirion-i2c crate was [updatede to 0.4.0](https://github.com/Sensirion/sensirion-i2c-rs/pull/30#issuecomment-2233408478), so this patch is not needed anymore.

2024-07-20 16:24 UTC, hawkw commented on Cargo.toml
> +sensirion-i2c = { git = "https://github.com/sensirion/sensirion-i2c-rs", rev = "f7b9f3a81b777bc6e6b2f0acb4c1ef9c57dfa06d" }
Great, sounds like we can now move forwards with this --- I'll go back and address your other feedback!

2024-07-20 16:27 UTC, hawkw commented on src/lib.rs
> +pub use async_impl::AsyncSgp30;
Honestly, I didn't think that hard about it. I'm fine with `Sgp30Async` if you prefer that. My thought process was that "async SGP30" was a more grammatically correct english phrase, since "async" is an adjective that would come before the noun. But, I agree that the more important information is that this is a SGP30 driver, so I'm happy to change it.

Ideally, I think, the name would be `async::Sgp30`, so that a user can reference it with that name or just import it from the `async` module if they're exclusively using the async API. But, "async" is a reserved word, so the only available options for the module name were less nice.

I'm happy to rename the type to `Sgp30Async`, I don't think there's a particularly strong established pattern except in code that I've written, where I've used the `AsyncFoo` naming scheme...

2024-07-20 16:28 UTC, hawkw commented on src/lib.rs
> +const SELFTEST_SUCCESS: &[u8] = &[0xd4, 0x00];
Sure, that seems good to me!

2024-07-20 16:33 UTC, hawkw commented on README.md
> +based on the [`embedded-hal`](https://github.com/japaric/embedded-hal) or
Sure --- would you prefer this to point to GitHub or crates.io?

2024-07-20 16:39 UTC, hawkw commented on src/lib.rs
> +        assert!(data.len() == 2 || data.len() == 4);
Added it in cb769b04bb07b8daa5ab0a807ad01849804534bf. 

Alternatively, it seems like we could probably just have two versions of this function that take 2- and 4-byte `data` buffers, and just call the appropriate one based on which command we're sending. That would avoid the runtime panic entirely, and also remove the branches. But, that seems like a larger refactor that I don't know if it makes sense to make as part of this change?

2024-07-20 16:39 UTC, hawkw commented on src/async_impl.rs
> +    // the ones in the `i2c` module.
Ah, I hadn't realized that, thanks! I'll add the same tests as the synchronous implementation.

2024-07-20 16:54 UTC, hawkw commented on src/async_impl.rs
> +    // the ones in the `i2c` module.
Done in 75d75e8e1540141e874b34b4069d9e4874897b96!

2024-07-20 16:54 UTC, hawkw commented on src/lib.rs
> +pub use async_impl::AsyncSgp30;
Renamed it to `Sgp30Async` in cb769b04bb07b8daa5ab0a807ad01849804534bf! :)

2024-07-20 16:55 UTC, hawkw commented
@dbrgn I believe I've addressed all your feedback, thanks for the review!

2024-07-21 12:45 UTC, dbrgn commented on README.md
> +based on the [`embedded-hal`](https://github.com/japaric/embedded-hal) or
I think https://docs.rs/embedded-hal/ would be best

2024-07-21 12:48 UTC, dbrgn commented on src/lib.rs
> +        assert!(data.len() == 2 || data.len() == 4);
Fair point! I created https://github.com/dbrgn/sgp30-rs/issues/21

2024-07-21 12:54 UTC, dbrgn commented
Perfect, thanks! I'll rebase your branch on top of `main` to get a working CI run.

This is now good to merge, but I'd still be interested in your thoughts on https://github.com/dbrgn/sgp30-rs/pull/19#pullrequestreview-2150201238

2024-07-21 13:03 UTC, dbrgn commented
Ah, seems like we need to bump the MSRV. I'll do that in a separate PR.

2024-07-21 16:21 UTC, hawkw commented
> Ah, seems like we need to bump the MSRV. I'll do that in a separate PR.

Ah, whoops, my bad, I didn't notice that --- what change requires the MSRV bump?

2024-07-21 16:21 UTC, hawkw commented on README.md
> +based on the [`embedded-hal`](https://github.com/japaric/embedded-hal) or
I'll point it at docs.rs instead, I agree that that would be better., personally --- I just went with the GitHub URL since that was what was there before.

2024-07-21 16:27 UTC, hawkw commented
> I generally agree about the choices regarding a separate struct with methods of the same name. However, just to explore the available options: A third approach would be keeping the same shared `Sgp30` struct, but implementing both sync and async methods through two separate traits. One (and only one) of them would need to be imported to bring in the desired methods. The separate struct is probably better for ease-of use though. What are your thoughts on that?

Personally, I don't love APIs where the core functionality is only present on a trait implementation that is only implemented by one type. I find it a bit of an annoying speed bump for a user to have to import both the type *and* the trait, and it's kind of easy for a new user to read an example and miss that it also requires a trait being implemented. The fact that you can't use `recv()` on the `futures` crate's MPSC channel without also importing `StreamExt` is an example of this kind of annoyance. With that said, I do think this option would work. I'm not sure if it makes things any better for the user than just having two types, though --- they still have to import one of two different names to indicate whether they want the async or blocking API, and since almost all the methods on the type do I2C transactions, there aren't really any methods that could be shared besides `new` and `destroy` AFAICT.

> Another thing I don't really like is how close-but-not-the-same the implementations are. I guess that's just how colored functions work in Rust. However, the commends are identical copies. Are you aware of a way to "inherit" docs of another method (maybe using a macro)?

I also don't love the code duplication --- I've tried to, at least, factor out all the shared code that's more complex than just "send this command" into free functions that both versions can use. Regarding docs, I think it would theoretically be possible to have a macro that generates both implementations, allowing the doc comment to only be written out once...but it would be quite complex, as it would need some way to know where the `.await`s go in the async version but elide them from the sync version.  I didn't think that would be worth the complexity. I'm willing to look into it if you think it would be better, though!

2024-07-21 16:53 UTC, dbrgn commented
> > Ah, seems like we need to bump the MSRV. I'll do that in a separate PR.
> 
> Ah, whoops, my bad, I didn't notice that --- what change requires the MSRV bump?

The embedded-hal-async crate: https://github.com/dbrgn/sgp30-rs/actions/runs/10028497153/job/27715481332

>  I didn't think that would be worth the complexity. I'm willing to look into it if you think it would be better, though!

Ah, examples would need to be different, true. But for cases where comments are 100% identical, such a macro might be useful.

In any case, I think this change is now ready to be merged! Thanks for your contribution.

2024-07-21 16:54 UTC, merged

2024-07-21 17:07 UTC, dbrgn commented
@hawkw I published version 1.0.0-rc.1 of this crate to crates.io. Testing in a real-world project (especially the async part) would be welcome! (I'll upgrade my non-async projects to this version as well.)

2024-07-21 17:45 UTC, hawkw commented
> @hawkw I published version 1.0.0-rc.1 of this crate to crates.io. Testing in a real-world project (especially the async part) would be welcome! (I'll upgrade my non-async projects to this version as well.)

I've been using the async code in [a personal hobby project](https://github.com/hawkw/eclssd) via a Git dep since I opened this branch, if that's helpful. I'm not using it in a commercial product, so there's maybe not quite the same level of rigor... I'll definitely switch from the Git dep to the crates.io version and let you know if anything has suddenly stopped working!